# Generated by Django 5.1.1 on 2024-11-09 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_student_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fk',
        ),
    ]
